"""Record & Replay export for CodeBites Form CRUD.

Auto-generated by Selenium IDE 'Export → Python pytest'. The brittle
auto-derived XPath locators are intentionally left as-is to faithfully
represent how a non-AI Record & Replay baseline behaves under DOM mutation.
"""
import pytest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC


@pytest.fixture
def driver():
    options = webdriver.ChromeOptions()
    options.add_argument("--headless=new")
    d = webdriver.Chrome(options=options)
    d.implicitly_wait(5)
    yield d
    d.quit()


def test_codebites_form_crud(driver):
    driver.get("http://localhost:3001/")
    driver.find_element(By.XPATH, "//header/nav/a[3]").click()  # Login
    driver.find_element(By.XPATH, "(//input)[1]").send_keys("tester@wideverse.local")
    driver.find_element(By.XPATH, "(//input)[2]").send_keys("Doc2Test!2026")
    driver.find_element(By.XPATH, "//button[@type='submit']").click()
    driver.find_element(By.XPATH, "//a[contains(.,'+ New recipe')]").click()
    driver.find_element(By.XPATH, "(//input)[1]").send_keys("Pasta alla Carbonara")
    driver.find_element(By.XPATH, "//textarea").send_keys(
        "Spaghetti, eggs, guanciale, pecorino, pepper"
    )
    driver.find_element(By.XPATH, "//button[@type='submit']").click()
    WebDriverWait(driver, 5).until(
        EC.presence_of_element_located((By.XPATH, "//ul/li[1]"))
    )
    assert "Pasta alla Carbonara" in driver.find_element(By.XPATH, "//ul").text
